feat: added custom tailwind config  and values component updated
wehelplive/wehelp.live pull request #46
Opened 2022-04-18 12:54 UTC by amanuela97

## Core values 

- Create core values section of homepage
- [demo](https://625d5ec70cfe40000871f226--wehelpdemo.netlify.app/)

2022-04-19 13:11 UTC, razbakov requested changes
@amanuela97 please make sure visually it looks same as on Figma: fonts, position of text, etc.

2022-04-21 11:54 UTC, razbakov requested changes

2022-04-21 11:54 UTC, razbakov commented on nuxt.config.js
> +      'Nunito sans-serif': true,
Check generated css code and network tab. I guess problem is here

2022-04-22 13:29 UTC, amanuela97 commented
> @amanuela97 please make sure visually it looks same as on Figma: fonts, position of text, etc.

2022-04-25 13:33 UTC, harshbrahmxatriya submitted a review, later dismissed

2022-04-25 13:33 UTC, harshbrahmxatriya commented on components/block/values.vue
>        </p>
Is prettier working when you save the file?

2022-04-25 20:19 UTC, razbakov commented
@amanuela97 please resolve the conflict

2022-04-28 19:37 UTC, razbakov requested changes
@amanuela97 check demo on desktop. Does it look OK to you? Please use some of TailwindUI components, that are responsive. Make it look good on desktop.

2022-04-28 20:04 UTC, amanuela97 commented
> @amanuela97 check demo on desktop. Does it look OK to you? Please use some of TailwindUI components, that are responsive. Make it look good on desktop.

should position of text be same on dekstop as in mobile ?

2022-05-16 13:42 UTC, razbakov approved these changes
LGTM

2022-05-16 13:42 UTC, merged