Vuepress doc
wehelplive/wehelp.live pull request #50
Opened 2022-05-03 12:43 UTC by amanuela97

## VuePress Doc

- setup a documentation site powered by vuepress
- [demo](https://wehelp-docs.netlify.app/)

2022-05-16 13:42 UTC, razbakov requested changes
Please resolve merge conflicts

2022-05-24 13:29 UTC, razbakov requested changes
Please use logo with icon only

2022-05-25 11:54 UTC, amanuela97 commented
> 1. Header: please use logo with icon only
> 2. Please import all pages from our handbook (Notion)

2022-05-26 11:37 UTC, razbakov approved these changes

2022-05-26 11:37 UTC, merged