Faq
wehelplive/wehelp.live pull request #52
Opened 2022-05-05 12:46 UTC by amanuela97

## FAQ Section

- [demo](https://wehelpdemo.netlify.app/)

2022-05-05 12:59 UTC, VOlekh commented on components/block/faq.vue
>  </template>
missing new line

2022-05-05 13:03 UTC, VOlekh commented on components/faq/item.vue
> +            class="font-nunito font-semibold text-[#2B2B2B] text-subtitle-2"
replace text-[#2B2B2B] with text-black-500

2022-05-05 13:06 UTC, VOlekh commented on components/block/faq.vue
> +      <div class="max-w-3xl mx-auto divide-y divide-[#C4C4C4]">
you have colors black-500, grey-300, neutral-500 take look on design in a black frame

2022-05-05 13:07 UTC, VOlekh commented on components/faq/item.vue
> +  <dl class="mt-6 space-y-6 divide-y divide-gray-200">
you only have  grey-300 in design

2022-05-05 13:08 UTC, VOlekh commented on components/faq/item.vue
> +            class="font-nunito font-semibold text-[#2B2B2B] text-subtitle-2"
color

2022-05-05 13:08 UTC, VOlekh commented on components/faq/item.vue
> +          class="text-left w-full flex justify-between items-start text-gray-400"
color

2022-05-05 13:10 UTC, VOlekh approved these changes
Need to add empty lines and change colors

2022-05-16 13:39 UTC, razbakov requested changes
1. Please resolve solved conversations in PR
2. Please update demo link in PR description

2022-05-16 14:05 UTC, razbakov approved these changes

2022-05-16 14:05 UTC, merged