feat: filter by service and city
wehelplive/wehelp.live pull request #76
Opened 2022-06-23 17:40 UTC by amanuela97

As a user, I would like to filter services based on the city and the service type. see https://trello.com/c/TnFo7mCd/310-filter-by-city & https://trello.com/c/5To9j8Z2/311-filter-by-service

## Acceptance Criteria
- [x] route `/services` displays all services
- [x] route `/services/:location?/ `displays services that match the location name
- [x] route `/services/:location?/:service?/` displays services that match the service type 
- [x] spinner is shown when data is loading

## Demo
https://deploy-preview-76--wehelpvip.netlify.app/services/

2022-06-23 17:47 UTC, razbakov requested changes
1) include direct link to test in your PR, i.e. https://deploy-preview-76--wehelpvip.netlify.app/
2) https://deploy-preview-76--wehelpvip.netlify.app/services/Munich - no results
3) I would rather do filter client-side, we don't have that many services yet, and it will work faster with less API requests

2022-06-23 17:47 UTC, razbakov commented on pages/services/index.vue
> +    console.log(this.services)
remove debug info

2022-06-23 17:49 UTC, razbakov requested changes
please change card border to gray like in https://wehelp.live/guests ?

2022-06-23 17:49 UTC, razbakov commented on utils/airtable.js
> +    console.log(param)
remove debug info

2022-06-23 17:49 UTC, razbakov commented on utils/airtable.js
> +      const array = ['Services'].includes(name)
that's strange

2022-06-23 17:54 UTC, razbakov requested changes

2022-06-23 17:54 UTC, razbakov commented on nuxt.config.js
> +import { resolve } from 'path'
see code example in https://v3.nuxtjs.org/examples/advanced/module-extend-pages/

```js
import { resolve } from 'pathe'
```

2022-06-27 11:43 UTC, Simran191997 commented
route /services displays all services
 route /services/:location?/ displays services that match the location name
 spinner is shown when data is loading

Above mentioned acceptance criteria is working fine  in android device ,ipad and laptop.

/services/:location?/:service?/ displays services that match the service type 

only the above one is not working fine.

2022-06-28 09:11 UTC, merged